/* Generated by scripts/train-crt.js — trained CRT 4H parameters and their results. */
window.CRT_TRAINED = {
  "generatedAt": "2026-10-01T04:09:15.148Z",
  "candles": 13348,
  "from": 1598616000000,
  "to": 1790812800000,
  "splitTime": 1733155200000,
  "combinations": 7776,
  "robustCount": 118,
  "cost": 0.4,
  "params": {
    "minRangeAtr": 0.75,
    "maxSweep": 0.5,
    "closeDepth": 0,
    "trend": "ema200",
    "target": "mid",
    "slBufferAtr": 0.5,
    "minRR": 0.75,
    "maxBars": 12,
    "skipWeekend": false
  },
  "train": {
    "trades": 41,
    "wins": 30,
    "winRate": 0.7317073170731707,
    "totalR": 15.285161878717496,
    "expectancy": 0.3728088263101828,
    "profitFactor": 2.3385762675968826,
    "maxDD": 2.106710748525466
  },
  "test": {
    "trades": 26,
    "wins": 12,
    "winRate": 0.46153846153846156,
    "totalR": -1.5875593673576986,
    "expectancy": -0.061059975667603794,
    "profitFactor": 0.8631217361420533,
    "maxDD": 4.584556989638443
  }
};
