#!/usr/bin/env node
/* Forward test: records every live signal of the 5-a-day rule set (js/intraday-data.js)
 * as it happens, with the time it was first seen, and fills in the result when the
 * trade closes. Run hourly by .github/workflows/forward-test.yml, which commits the
 * log — the commit history is a timestamped, tamper-evident track record.
 * Writes data/forward/signals.json and js/forward-data.js. */
const fs = require('fs');
const path = require('path');
const History = require('../../js/history.js');
const L = require('../research/lib.js');

const root = path.join(__dirname, '../..');
const FORWARD_START = Date.UTC(2026, 9, 8); // trades entered from 8 Oct 2026 onward
const file = path.join(root, 'data/forward/signals.json');
const src = fs.readFileSync(path.join(root, 'js/intraday-data.js'), 'utf8');
const D = JSON.parse(src.slice(src.indexOf('{'), src.lastIndexOf('}') + 1));
const tfName = (tf) => (tf === 60 ? '1H' : tf === 240 ? '4H' : tf + 'm');
const toRows = (a) => a.filter((c) => c.closed).map((c) => [c.time, c.open, c.high, c.low, c.close]);

(async () => {
  const now = Date.now();
  const log = fs.existsSync(file) ? JSON.parse(fs.readFileSync(file, 'utf8')) : { started: new Date(FORWARD_START).toISOString(), riskPct: D.riskPct, cost: D.cost, rules: D.legs.map((l) => `${tfName(l.tf)} ${l.label}`), signals: [] };
  const [m15, m30, h1raw] = await Promise.all([
    History.fetchRange('15m', now - 3000 * 900e3), History.fetchRange('30m', now - 3000 * 1800e3), History.fetchRange('1h', now - 3000 * 3600e3),
  ]);
  const h1 = L.build(toRows(h1raw), 60), h4 = L.build(toRows(h1raw), 240);
  const frames = { 15: L.build(toRows(m15), 15), 30: L.build(toRows(m30), 30), 60: h1, 240: h4 };
  for (const [tf, c] of Object.entries(frames)) c.htf = { h1: L.htfTrend(c, +tf, h1, 60), h4: L.htfTrend(c, +tf, h4, 240) };

  const byKey = new Map(log.signals.map((s) => [s.key, s]));
  let added = 0, closed = 0;
  for (const l of D.legs) {
    const rule = `${tfName(l.tf)} ${l.label}`;
    for (const t of L.backtest(frames[l.tf], L.STRATS[l.id], l.params, { cost: D.cost })) {
      if (t.entryTime < FORWARD_START) continue;
      const key = `${l.tf}-${l.id}-${t.entryTime}-${t.dir}`;
      let s = byKey.get(key);
      if (!s) {
        s = { key, rule, side: t.dir === 1 ? 'BUY' : 'SELL', entryTime: new Date(t.entryTime).toISOString(), firstSeen: new Date(now).toISOString(), entry: +t.entry.toFixed(2), stop: +t.stop.toFixed(2), target: t.target != null ? +t.target.toFixed(2) : null, status: 'open' };
        byKey.set(key, s); log.signals.push(s); added++;
      }
      if (s.status === 'open' && t.why !== 'end') {
        Object.assign(s, { status: 'closed', exitTime: new Date(t.exitTime).toISOString(), exit: +t.exit.toFixed(2), why: t.why, r: +t.r.toFixed(3) });
        closed++;
      }
    }
  }
  log.signals.sort((a, b) => a.entryTime.localeCompare(b.entryTime));
  const done = log.signals.filter((s) => s.status === 'closed');
  let eq = 1, peak = 1, dd = 0;
  for (const s of [...done].sort((a, b) => a.exitTime.localeCompare(b.exitTime))) { eq *= 1 + (D.riskPct / 100) * s.r; peak = Math.max(peak, eq); dd = Math.max(dd, 1 - eq / peak); }
  const days = Math.max(1, (now - FORWARD_START) / 86400e3 * 5 / 7);
  log.summary = {
    updated: new Date(now).toISOString(), signals: log.signals.length, open: log.signals.length - done.length, closed: done.length,
    winRate: done.length ? done.filter((s) => s.r > 0).length / done.length : null, totalR: +done.reduce((a, s) => a + s.r, 0).toFixed(3),
    returnPct: +((eq - 1) * 100).toFixed(2), maxDDPct: +(dd * 100).toFixed(2), perDay: +(log.signals.length / days).toFixed(2),
  };
  fs.mkdirSync(path.dirname(file), { recursive: true });
  fs.writeFileSync(file, JSON.stringify(log, null, 1) + '\n');
  fs.writeFileSync(path.join(root, 'js/forward-data.js'), '/* Generated by scripts/forward/log.js */\nwindow.FORWARD = ' + JSON.stringify(log) + ';\n');
  console.log(`forward log: +${added} new, ${closed} closed · ${log.summary.signals} signals since ${log.started.slice(0, 10)} · closed ${done.length} · total ${log.summary.totalR}R`);
})().catch((e) => { console.error(e); process.exit(1); });
