#!/usr/bin/env node
/* Writes js/events-data.js (window.EVENTS) from data/events/us-macro-events.json so the
 * news countdown works on every page without fetching JSON (file:// friendly). */
const fs = require('fs');
const path = require('path');
const root = path.join(__dirname, '..');
const src = JSON.parse(fs.readFileSync(path.join(root, 'data/events/us-macro-events.json'), 'utf8'));
const events = src.events.map((e) => [e.type, e.date, e.timeNY]);
const last = src.events.at(-1).date;
fs.writeFileSync(path.join(root, 'js/events-data.js'),
  `/* Generated by scripts/build-events.js from data/events/us-macro-events.json — ${src.source}. */\nwindow.EVENTS = ${JSON.stringify({ last, events })};\n`);
console.log(`js/events-data.js: ${events.length} events, last ${last}`);
