#!/usr/bin/env node
/* Downloads 4H gold history, trains the CRT strategy (grid search on the oldest 70%,
 * tested on the newest 30%), and writes:
 *   data/paxg-4h.csv        recorded candle history
 *   data/crt-report.json    full training report
 *   js/crt-trained.js       trained parameters used by the website by default
 * Usage: node scripts/train-crt.js   (behind a proxy: NODE_USE_ENV_PROXY=1 node ...) */
const fs = require('fs');
const path = require('path');
const History = require('../js/history.js');
const CRT = require('../js/crt.js');

const root = path.join(__dirname, '..');
const pct = (v) => (v * 100).toFixed(1) + '%';
const line = (name, s) => console.log(
  `${name.padEnd(6)} trades ${String(s.trades).padStart(4)}  win ${pct(s.winRate).padStart(6)}  ` +
  `PF ${s.profitFactor.toFixed(2)}  exp ${s.expectancy.toFixed(3)}R  total ${s.totalR.toFixed(1)}R  maxDD ${s.maxDD.toFixed(1)}R`);

(async () => {
  console.log('Downloading 4H history…');
  const candles = await History.fetchRange('4h', 0);
  const closed = candles.filter((c) => c.closed);
  fs.writeFileSync(path.join(root, 'data/paxg-4h.csv'), History.toCSV(closed));
  console.log(`Recorded ${closed.length} candles ${new Date(closed[0].time).toISOString()} → ${new Date(closed.at(-1).time).toISOString()}`);

  const base = CRT.backtest(closed, CRT.DEFAULT_PARAMS).stats;
  line('Untrained', base);

  console.log(`Training on ${CRT.combos(CRT.GRID).length} parameter combinations…`);
  const res = await CRT.optimize(closed, { split: 0.7, minTrades: 40 });
  if (!res.best) throw new Error('No parameter set produced enough trades');
  console.log(`${res.robustCount} combinations were profitable consistently across the training slices (cost $${res.cost}/trade).`);
  console.log('Best parameters:', res.best.params);
  line('Train', res.best.train);
  line('Test', res.best.test);
  const full = CRT.backtest(closed, res.best.params).stats;
  line('All', full);

  const strip = (s) => ({ ...s, equity: undefined });
  const report = {
    generatedAt: new Date().toISOString(), symbol: History.SYMBOL, interval: '4h',
    candles: closed.length, from: closed[0].time, to: closed.at(-1).time, splitTime: res.splitTime,
    combinations: res.tested, robustCount: res.robustCount, cost: res.cost, untrained: strip(base),
    best: { params: res.best.params, train: strip(res.best.train), test: strip(res.best.test), all: strip(full) },
    top: res.top.map((r) => ({ params: r.params, folds: r.folds, train: strip(r.train), test: strip(r.test) })),
  };
  fs.writeFileSync(path.join(root, 'data/crt-report.json'), JSON.stringify(report, null, 2) + '\n');
  fs.writeFileSync(path.join(root, 'js/crt-trained.js'),
    '/* Generated by scripts/train-crt.js — trained CRT 4H parameters and their results. */\n' +
    `window.CRT_TRAINED = ${JSON.stringify({ generatedAt: report.generatedAt, candles: report.candles, from: report.from, to: report.to, splitTime: report.splitTime, combinations: report.combinations, robustCount: report.robustCount, cost: report.cost, params: report.best.params, train: report.best.train, test: report.best.test }, null, 2)};\n`);
  console.log('Wrote data/paxg-4h.csv, data/crt-report.json, js/crt-trained.js');
})().catch((e) => { console.error(e); process.exit(1); });
